### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by archisha69** [balls8/reflect-os#9]
not an issue

**Comment by thatOneArchUser** [comment]
> not an issue

oh ok

**Comment by archisha69** [comment]
literally dont know what am i doing rn

**Comment by thatOneArchUser** [comment]
you are commenting in your issue

**Comment by archisha69** [comment]
0

**Comment by archisha69** [comment]
no we are literally chatting inside an issue that is not an issue

**Comment by archisha69** [comment]
bro pinned this :skull:
